version: '3.3'

services:
  php:
    image: accounting_php
    restart: always
    volumes:
      - ./src:/home/app/src:Z
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /home/app/src

  nginx:
    image: nginx:1.23.0-alpine
    restart: always
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./src:/home/app/src
    links:
      - php
    ports:
      - "0.0.0.0:32001:80"
    working_dir: /home/app/src

volumes:
  composer-cache:
